In [2]:
hi = "hi"

print(hi)

hi


In [6]:
import numpy.linalg as npl
import numpy as np
a = np.random.randn(9).reshape(3, 3)
unit_a = a/npl.norm(a)

print(np.abs(unit_a))

[[0.1473177  0.34015423 0.17839515]
 [0.27750312 0.14594372 0.43488234]
 [0.03728691 0.58060819 0.45259405]]
